baseurl = "/"
languageCode = "en-us"
title = "Jian | 黄俭"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"


[[menu.main]]
    name = "主页"
    url = "/home/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "博客"
    url = "/"
    weight = 3

[params]
    description = "Powered by Hugo"
    footer = "&copy; [Jian Huang](https://huangjianseven.name) 2008 - 2018 | [Github](https://github.com/huangjianseven) | [Twitter](https://twitter.com/spirulina)"


  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
